#!/usr/bin/env python3
"""Compile vertex/edge wireframes into Cthugha .obj line segments. See the adjacent irregular-tetrahedron.wire for an example."""

import argparse
import re
import sys


SECTION_VERTICES = "vertices"
SECTION_EDGES = "edges"


def parse_ints(line, lineno, expected, section):
    values = re.findall(r"[-+]?\d+", line)
    if not values:
        return None
    if len(values) != expected:
        raise ValueError(
            f"line {lineno}: expected {expected} integers in {section}, got {len(values)}"
        )
    return tuple(int(value) for value in values)


def read_wireframe(path):
    vertices = []
    edges = []
    section = None

    with open(path, "r", encoding="utf-8") as source:
        for lineno, line in enumerate(source, 1):
            stripped = line.strip()
            if not stripped:
                continue

            marker = stripped.upper()
            if marker == "#VERTICES":
                section = SECTION_VERTICES
                continue
            if marker == "#EDGES":
                section = SECTION_EDGES
                continue
            if stripped.startswith("#"):
                continue
            if section is None:
                raise ValueError(f"line {lineno}: data appears before a section marker")

            if section == SECTION_VERTICES:
                parsed = parse_ints(stripped, lineno, 3, section)
                if parsed is not None:
                    vertices.append(parsed)
            else:
                parsed = parse_ints(stripped, lineno, 2, section)
                if parsed is not None:
                    edges.append(parsed)

    if not vertices:
        raise ValueError("no vertices found")
    if not edges:
        raise ValueError("no edges found")

    for edge_no, (start, end) in enumerate(edges, 1):
        if start < 0 or start >= len(vertices):
            raise ValueError(f"edge {edge_no}: start vertex index {start} is out of range")
        if end < 0 or end >= len(vertices):
            raise ValueError(f"edge {edge_no}: end vertex index {end} is out of range")

    return vertices, edges


def write_cthugha_obj(vertices, edges, path):
    with open(path, "w", encoding="utf-8") as target:
        target.write("# Generated by tools/compile-wire-obj.py\n")
        for start, end in edges:
            x1, y1, z1 = vertices[start]
            x2, y2, z2 = vertices[end]
            target.write(f"{x1},{y1},{z1} - {x2},{y2},{z2}\n")


def main():
    parser = argparse.ArgumentParser(
        description="Compile #VERTICES/#EDGES wireframes into Cthugha .obj files."
    )
    parser.add_argument("input", help="wireframe source file")
    parser.add_argument("output", help="Cthugha .obj output path")
    args = parser.parse_args()

    try:
        vertices, edges = read_wireframe(args.input)
        write_cthugha_obj(vertices, edges, args.output)
    except (OSError, ValueError) as exc:
        print(f"compile-wire-obj.py: {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
