// Defaults for typed startup configuration slices.

#ifndef CTHUGHA_CONFIGURATION_DEFAULTS_H
#define CTHUGHA_CONFIGURATION_DEFAULTS_H

#include "AudioTypes.h"
#include "cthugha.h"

static const int LOGGING_CONFIG_DEFAULT_VERBOSITY = 1;

static const int APP_CONFIG_DEFAULT_OPTIONS_SAVE_ENABLED = 0;

static const int INPUT_CONFIG_DEFAULT_ESCAPE_KEY_ENABLED = 1;
#define INPUT_CONFIG_DEFAULT_KEYMAP_FILE_PATH ""

static const int AUTO_CHANGE_CONFIG_DEFAULT_QUIET_MS = 1500;
static const int AUTO_CHANGE_CONFIG_DEFAULT_WAIT_MIN_MS = 3000;
static const int AUTO_CHANGE_CONFIG_DEFAULT_WAIT_RANDOM_MS = 11000;
static const int AUTO_CHANGE_CONFIG_DEFAULT_WAIT_RANDOM_MIN_MS = 1;
static const int AUTO_CHANGE_CONFIG_DEFAULT_CUMULATIVE_FIRE_LEVEL = 1000;
static const int AUTO_CHANGE_CONFIG_DEFAULT_LOCKED = 0;
static const int AUTO_CHANGE_CONFIG_DEFAULT_CHANGE_LITTLE = 0;
static const int AUDIO_ANALYSIS_CONFIG_DEFAULT_MIN_NOISE = 5;

static const int EFFECT_POLICY_DEFAULT_IMAGE_FILES_ENABLED = 1;
static const int EFFECT_POLICY_DEFAULT_USE_TRANSLATES_ENABLED = 1;
static const int EFFECT_POLICY_DEFAULT_USE_OBJECTS_ENABLED = 1;
#define EFFECT_POLICY_DEFAULT_PALETTE_SET_FILTER_TEXT ""

static const double SCENE_TRANSITION_POLICY_DEFAULT_PALETTE_SMOOTHING_CHANCE = 1.0;
static const int SCENE_TRANSITION_POLICY_DEFAULT_PALETTE_SMOOTH_SECONDS = 2;

static const int AUDIO_CONFIG_DEFAULT_INPUT_LOOP_ENABLED = 1;
static const AudioInputMode AUDIO_CONFIG_DEFAULT_INPUT_MODE = AIM_DSPIn;
static const int AUDIO_CONFIG_DEFAULT_SAMPLE_RATE_HZ = 44000;
static const int AUDIO_CONFIG_DEFAULT_CHANNELS = 2;
static const AudioSampleFormat AUDIO_CONFIG_DEFAULT_FORMAT = SF_u8;
static const int AUDIO_CONFIG_DEFAULT_DSP_METHOD = 0;
static const int AUDIO_CONFIG_DEFAULT_DSP_FRAGMENTS = 16;
static const int AUDIO_CONFIG_DEFAULT_DSP_FRAGMENT_SIZE = 0;
static const int AUDIO_CONFIG_DEFAULT_DSP_SYNC_ENABLED = 0;
static const int AUDIO_CONFIG_DEFAULT_SILENT_ENABLED = 0;
static const AudioOutputDriverId AUDIO_CONFIG_DEFAULT_OUTPUT_DRIVER
    = AudioOutputDriverAuto;
static const int AUDIO_CONFIG_DEFAULT_MIXER_VOLUME = 0;
static const int AUDIO_CONFIG_DEFAULT_PULSE_LATENCY_MS = 250;
static const int AUDIO_CONFIG_DEFAULT_NULL_TARGET_LATENCY_MS = 0;
static const int AUDIO_CONFIG_DEFAULT_PULSE_TARGET_LATENCY_MS = 250;
static const int AUDIO_CONFIG_DEFAULT_MINIAUDIO_TARGET_LATENCY_MS = 250;
static const int AUDIO_CONFIG_DEFAULT_DSP_TARGET_LATENCY_MS = 250;
#define AUDIO_CONFIG_DEFAULT_PULSE_SERVER_TEXT ""
#define AUDIO_CONFIG_DEFAULT_OUTPUT_DUMP_PATH ""
#define AUDIO_CONFIG_DEFAULT_INPUT_FILE_PATH ""
#define AUDIO_CONFIG_DEFAULT_MINIAUDIO_PLAYBACK_DEVICE_NAME ""
#define AUDIO_CONFIG_DEFAULT_MINIAUDIO_CAPTURE_DEVICE_NAME ""

#if WITH_DSP == 1
#define AUDIO_CONFIG_DEFAULT_DSP_DEVICE_PATH DEV_DSP
#else
#define AUDIO_CONFIG_DEFAULT_DSP_DEVICE_PATH ""
#endif

#if WITH_MIXER == 1
#define AUDIO_CONFIG_DEFAULT_MIXER_DEVICE_PATH DEV_MIXER
#else
#define AUDIO_CONFIG_DEFAULT_MIXER_DEVICE_PATH ""
#endif

static const int DISPLAY_CONFIG_DEFAULT_MAX_FRAMES_PER_SECOND = 25;
static const int DISPLAY_CONFIG_DEFAULT_SHOW_FPS_ENABLED = 0;
static const int DISPLAY_CONFIG_DEFAULT_ZOOM_MODE = 0;
static const int DISPLAY_CONFIG_DEFAULT_MODE = 0;

#ifdef CTH_XWIN
static const int X11_CONFIG_DEFAULT_OVERRIDE_REDIRECT = 0;
static const int X11_CONFIG_DEFAULT_PRIVATE_CMAP = 0;
static const int X11_CONFIG_DEFAULT_MIT_SHM = 1;
static const int X11_CONFIG_DEFAULT_ROOT_WINDOW = 0;
static const int X11_CONFIG_DEFAULT_FULLSCREEN = 0;
static const int X11_CONFIG_DEFAULT_WINDOW_POSITION_ENABLED = 0;
static const int X11_CONFIG_DEFAULT_WINDOW_POSITION_X = 0;
static const int X11_CONFIG_DEFAULT_WINDOW_POSITION_Y = 0;
static const int X11_CONFIG_DEFAULT_PANEL_ENABLED = 0;
#define X11_CONFIG_DEFAULT_FONT_NAME "-adobe-courier-medium-r-normal--14-*-100-100-m-*-*-*"
#define X11_CONFIG_DEFAULT_FRAME_DUMP_DIRECTORY ""
static const int X11_CONFIG_DEFAULT_FRAME_DUMP_LIMIT = 1;
static const int X11_CONFIG_DEFAULT_FRAME_DUMP_EVERY = 1;
#endif

#define PATH_CONFIG_DEFAULT_EXTRA_LIBRARY_PATH ""
#define PATH_CONFIG_DEFAULT_INI_FILE_OVERRIDE_PATH ""

static const int MESSAGES_CONFIG_DEFAULT_QOTD_PREFETCH_TIMEOUT_MS = 500;
static const int MESSAGES_CONFIG_DEFAULT_QUIET_MESSAGE_MS = 10000;
static const int MESSAGES_CONFIG_DEFAULT_QUIET_MESSAGE_DURATION_MS = 6000;
static const int MESSAGES_CONFIG_DEFAULT_QOTD_ENABLED = 0;
static const char* MESSAGES_CONFIG_DEFAULT_QUIET_MESSAGE_FILE_PATH = "";
static const char* MESSAGES_CONFIG_DEFAULT_QOTD_SERVER_TEXT = "djxmmx.net:17";
static const char* MESSAGES_CONFIG_DEFAULT_QOTD_PORT_TEXT = "17";

#endif
