if(NOT DEFINED INPUT)
    message(FATAL_ERROR "INPUT is required")
endif()
if(NOT DEFINED OUTPUT)
    message(FATAL_ERROR "OUTPUT is required")
endif()

file(STRINGS "${INPUT}" keymap_lines)
file(WRITE "${OUTPUT}" "")
foreach(line IN LISTS keymap_lines)
    string(REPLACE "\\" "\\\\" escaped "${line}")
    string(REPLACE "\"" "\\\"" escaped "${escaped}")
    file(APPEND "${OUTPUT}" "\"${escaped}\",\n")
endforeach()
